### ISSUE TITLE
Reusing react-dag with existing store

### ISSUE THREAD

**Issue by vu3mmg** [ajainarayanan/react-dag#1]
Hi,
Could you please give me some  hints about reusing react DAG with  existing react redux project .

How will it interact with <Provider >.

regards
Mahesh

**Comment by ajainarayanan** [comment]
Sorry for the late response.

@vu3mmg Could you give some background? react-dag just uses existing react and redux that you already have in your environment. I have been using react-dag in an app that I am [trying here](https://github.com/ajainarayanan/react-dag-app). I am assuming that you are using webpack or using react and redux from a global object.

**Comment by vu3mmg** [comment]
Thanks for the replay .

I am creating a meteor app . From the explanation , i thought we need to
setup another store  for DAG library .
I will read it again .
