### ISSUE TITLE
update jsplumb

### ISSUE THREAD

**Issue by wulucxy** [ajainarayanan/react-dag#11]
hi, @ajainarayanan jsplumb has update to version 2.5.1, do you have plan to update to the new version?

**Comment by ajainarayanan** [comment]
Hi @wulucxy Right now I am held up with work. Might not be in the near future (like 1-2 weeks) but will aim by end of September. Feel free to create a PR upgrading the version (do run over the tests and local dev mode)

**Comment by wulucxy** [comment]
@ajainarayanan thanks for the feedback. I have another question, I can't find the source code of the demo, so how can i test the component in this repo?

**Comment by ajainarayanan** [comment]
@wulucxy I have re-written the entire component and the new version has jsplumb version `2.5.12`. Feel free to try the new component available as part of `2.0.0.alpha.1` version of react-dag (https://github.com/ajainarayanan/react-dag/tree/feature/ui-2.0.0.alpha.1)
