### ISSUE TITLE
opensource the demo source code?

### ISSUE THREAD

**Issue by wf123537200** [ajainarayanan/react-dag#14]
i want 2 draw the same canvas, but the code of the demo has been mix up.
would you please opensource the demo source code
3q very much!

**Comment by ajainarayanan** [comment]
Hi @wf123537200 . Sorry for the confusion. The changes are in the `feature/ui-2.0.0.alpha.1` branch and I missed to make it the default branch.

I have now made the changes you should be able to go to https://github.com/ajainarayanan/react-dag-app and have it load the src for the graph you see in the demo.

#### EDIT:
  I just noticed that the demo link points to the old design and the branch I gave you has the re-write code. Right now I am not able to spend time in fixing this issue, so here is the gist,

- Old code ([master branch](https://github.com/ajainarayanan/react-dag-app/tree/master) = [demo link](http://react-dag-app.surge.sh/)
- New code ([feature/ui-2.0.0.alpha.1](https://github.com/ajainarayanan/react-dag-app/tree/feature/ui-2.0.0.alpha.1)) != no demo available yet.

Give me sometime to sort this out over ⏳ .

**Comment by wf123537200** [comment]
ok, 3q very much!
it really help me a lot
