### ISSUE TITLE
How to bind node click event?

### ISSUE THREAD

**Issue by mathanpt** [ajainarayanan/react-dag#21]
I want to bind the click event for the nodes, from the jsplumb [doc](https://jsplumbtoolkit.com/community/doc/events.html) I don't find any click event for nodes

How do I implement the click event on nodes?

**Comment by ajainarayanan** [comment]
@mathanpt A node in react-dag is something defined by the developer. From the dev example we have in this repo https://github.com/ajainarayanan/react-dag/blob/feature/2.0.0.alpha/dev/components/NodeType1/index.tsx#L68 you can add a onClick handler on the nodes you define. This is not something that react-dag controls.

Hope that helps.

**Comment by mathanpt** [comment]
Thanks @ajainarayanan
