### ISSUE TITLE
Deleting a node with connections

### ISSUE THREAD

**Issue by mkm279** [ajainarayanan/react-dag#24]
I am using ReactDAG for creating a workflow management tool. 

Everytime I delete a node and pass the updated nodes and connections to reactDAG, the UI gets all messed up. I am not sure where am I going wrong. Any help would be greatly appreciated.

UI with nodes and connections
<img width="1680" alt="Screen Shot 2019-03-27 at 11 59 35 AM" src="https://user-images.githubusercontent.com/19628347/55055093-fdc71300-5087-11e9-94ae-51cbc7597486.png">

UI after deleting notification node
<img width="1679" alt="Screen Shot 2019-03-27 at 12 00 02 PM" src="https://user-images.githubusercontent.com/19628347/55055150-2bac5780-5088-11e9-88e7-ae1492b132e5.png">

**Comment by mkm279** [comment]
@ajainarayanan Can you please provide an example for onDelete props?

**Comment by ajainarayanan** [comment]
@mkm279 Hhmm seems weird. Right now a little bit overwhelmed with work. Let me try to spend sometime and see what is going on. Do you happen to have a codesandbox to replicate this error?

**Comment by mkm279** [comment]
@ajainarayanan Sorry that I am not able to provide a sandbox. Have been quite busy. I will try to create one over the weekend. What I am able to figure out so far is connections/endpoints inside jsplumb are not getting cleaned properly. Maybe there should be some cleanup function to call when the node unmounts which will clear all connections/endpoints related to it from jsplumb
