### ISSUE TITLE
onDelete() typings not in dist 2.0.0-alpha-5

### ISSUE THREAD

**Issue by benswinburne** [ajainarayanan/react-dag#26]
The changes made to the `interface INodeProps` made in https://github.com/ajainarayanan/react-dag/commit/f3258b3b89f1dd84ed30dd12eafdadd86be4ffae#diff-87b8af5581ac9180d1633b288fd10975R10 don't appear to be reflected in the release 2.0.0-alpha-5 on npm.

Having cloned `"react-dag": "^2.0.0-alpha-5"` the typings in `index.d.ts` still appear as follows.

```
export interface INodeProps {
  id: string;
  config?: INodeConfig;
  initNode?: (initConfig: IInitNodeProps) => void;
  onDelete?: () => void;
}

```

Which obviously results in TS complaining.

> Expected 0 arguments, but got 2. [Error/2554]

**Comment by ajainarayanan** [comment]
Oh hhmm @benswinburne. Need to check on this.
