### ISSUE TITLE
Are there plans to upgrade to jsplumb 4?

### ISSUE THREAD

**Issue by Vadorequest** [ajainarayanan/react-dag#43]
Jsplumb 4 is still in beta, but I wanted to know if you have any plan to upgrade the current implementation?

I don't know jsplumb at all, but the major improvement I can see is that it uses TypeScript, meaning a much better Developer Experience overall.

**Comment by ajainarayanan** [comment]
Closing this one as we are talking about upgrade in this issue: https://github.com/ajainarayanan/react-dag/issues/44
