### ISSUE TITLE
Are there plans to upgrade to jsplumb 2.15.x+?

### ISSUE THREAD

**Issue by Vadorequest** [ajainarayanan/react-dag#44]
I took a look at what version of jsplumb is being used by react-dag.

It seems the version is `2.5.12`, which seems to be 3 years old.

Here is a diff between the jsplumb 2.5.12 vs 2.15.4 (latest 2.x version):
https://github.com/jsplumb/jsplumb/compare/2.5.12...2.15.4

Note that most changes are about doc/demo/dist until the `package.json` file (about half of the changes aren't really interesting to look at)

I don't know if upgrading would provide any benefits, I assume so. (the API seems to have changed a lot). I noticed a react-dag v2 is in progress, but I'm not sure what its purpose is. 😃

**Comment by ajainarayanan** [comment]
@Vadorequest It looks like a lot of effort. Currently I don't have any plans but if you would like to contribute we can collaborate!

**Comment by Vadorequest** [comment]
Thanks for letting me know! Meanwhile I've found a better lib for my particular use case, so I won't likely contribute to jsplumb in a shortcoming future. 😄
