### ISSUE TITLE
Enable GitHub Discussions on this repository

### ISSUE THREAD

**Issue by Vadorequest** [ajainarayanan/react-dag#45]
GitHub recently released (in beta) their GitHub Discussions feature.

It looks like this: https://github.com/vercel/next.js/discussions

It's great for questions that aren't bugs or feature requests. Overall, it reduces the work for maintainers. I think this repository might be able to benefit from it!

You should be able to enable it in the repository settings. 

![image](https://user-images.githubusercontent.com/3807458/102009895-cce6b000-3d3a-11eb-8e51-bbea014c96d0.png)

**Comment by ajainarayanan** [comment]
@Vadorequest Done. Thanks!
